spring:
  application:
    name: ProductService

  datasource:
    url: jdbc:postgresql://localhost:5432/productservice
    username: uproductservice
    password: micproductservice
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    #http://localhost:8082/swagger-ui/index.html

server:
  port: 8082
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024 # Habilita compresión para respuestas grandes.
    max-http-header-size: 8192 # Ajusta para soportar headers más largos si es necesario.
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 10000
    connection-timeout: 5000 # Tiempo de espera en ms.

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true # Exposición de métricas en Prometheus.

app:
  micro: PRODUCTSERVICE
  environment: DES