server:
  port: 8090

spring:
  application:
    name: productservice

web:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:45438/railway
    username: postgres
    password: ObcggQODCkrLSYnzzLbvkieYDXMpmbsz
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum:
        pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
