spring:
  datasource:
    url: jdbc:h2:mem:builddb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
