version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "8080:80"  # Exponer el puerto 8080 en el host para acceder a pgAdmin
    networks:
      - postgres_network
    depends_on:
      - postgres  # Asegura que pgAdmin se levante después de Postgres

networks:
  postgres_network:
    driver: bridge